// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImageLink(arg1) {
  return window['go']['main']['App']['ImageLink'](arg1);
}

export function InitialFile() {
  return window['go']['main']['App']['InitialFile']();
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickImage() {
  return window['go']['main']['App']['PickImage']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReloadFile() {
  return window['go']['main']['App']['ReloadFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}

export function SetModified(arg1) {
  return window['go']['main']['App']['SetModified'](arg1);
}
