// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportHTML(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function ImageLink(arg1:string):Promise<string>;

export function InitialFile():Promise<main.FileResult>;

export function NewFile():Promise<void>;

export function OpenFile():Promise<main.FileResult>;

export function OpenPath(arg1:string):Promise<main.FileResult>;

export function PickImage():Promise<string>;

export function Quit():Promise<void>;

export function ReloadFile():Promise<main.FileResult>;

export function SaveFile(arg1:string):Promise<main.FileResult>;

export function SaveFileAs(arg1:string):Promise<main.FileResult>;

export function SetModified(arg1:boolean):Promise<void>;
